version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'

  api:
    build: .
    container_name: my_api
    depends_on:
      - redis
    environment:
      DATABASE_URL: postgres://user:password@host.docker.internal:5432/postgres
      REDIS_URL: redis://redis:6379
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: ['sh', '-c', 'npm install && npm run dev']
